Prepare release 1.2.0
git-big-picture/git-big-picture pull request #187
Opened 2022-02-28 18:08 UTC by hartwork

2022-03-01 09:49 UTC, esc requested changes
I trawled the source code for any other references to the version. Seems good to me. Only the month needs updating and this will be ready for launch! 🚀

2022-03-01 09:49 UTC, esc commented on README.rst
> +* ``v1.2.0`` — 2022-02-28
It's now march.

2022-03-01 09:49 UTC, esc commented on git-big-picture.1
> +.TH GIT-BIG-PICTURE "1" "February 2022" "git-big-picture 1.2.0" "User Commands"
also march

2022-03-01 14:32 UTC, merged

2022-03-01 14:45 UTC, hartwork commented
@esc merged and released. If you like to tweet about it, please feel encouraged to

2022-03-02 16:35 UTC, esc commented
> @esc merged and released. If you like to tweet about it, please feel encouraged to

Sure: https://twitter.com/esc___/status/1499060753285926921