Stop leaving temp files behind (alternative to #25)
git-big-picture/git-big-picture pull request #49
Opened 2020-12-30 19:44 UTC by hartwork

Inspired by original pull request #25 by @fredden

2021-01-01 19:36 UTC, esc commented
I wonder if there is any way to test this?

2021-01-01 20:19 UTC, hartwork commented
> I wonder if there is any way to test this?

If you like the general direction I can add tests on top. I have an idea how to do that in Cram/Scruf. It would be good to have a decision on #50 first so I'm sure I work into the right direction.

2021-01-04 22:10 UTC, hartwork commented
Rebased onto latest `master` (which includes #50) and added a simple test now.

2021-01-05 20:08 UTC, esc requested changes
I reviewed it by testing it on my local machine. I used `--debug` to trace that the file is created and that the wait time is read from the settings and applied correctly. Also in the case of `1`. I can confirm the file is deleted and also I can confirm that the viewer will not find the file if it is deleted too early. I also manually examined the test case and can confirm that it appears to work as intended. I left a few minor language nitpicks -- but the PR is ready to merge once the nitpicks have been addressed. 

`debug:   Value for 'wait' found in 'conf file', overrides setting '2.0' from 'defaults': '1.0'` <--- this line made me smile in the output.

2021-01-05 20:18 UTC, hartwork commented on test.scf
> +    $ ls -1 "$(git-big-picture -d -v true | fgrep 'temp file' | tee /dev/stderr | grep -Eo "/[^']+" | uniq)"
Sure! Pattern `/[^']+` is meant to match an absolute filename — some string starting with a slash —, the tempfile. It's enclosed in the output by single ticks left and right so I used `[^']` — anything but a single tick — to capture the full filename but not the closing tick. grep option `-o` ("only") drops the parts left and right of the match from any matching lines and `-E` ("extended") is to keep the regex more readable and not have `+` need to be `\+` (but it's not too important).

2021-01-05 20:30 UTC, hartwork commented on README.rst
> +                            their behalf, to then shut down themselves
Sure! Fixed x2

2021-01-05 20:31 UTC, hartwork commented on git-big-picture
> +                #       As a result, for a long-running process we don't wait more for nothing.
Done

2021-01-05 20:50 UTC, esc commented on test.scf
> +    $ ls -1 "$(git-big-picture -d -v true | fgrep 'temp file' | tee /dev/stderr | grep -Eo "/[^']+" | uniq)"
Thank you for clarification, that was very helpful.

2021-01-05 20:51 UTC, esc approved these changes
Looks good, ready for merge.

2021-01-05 20:51 UTC, merged