Add manpage from Debian package
git-big-picture/git-big-picture pull request #79
Opened 2021-01-14 21:20 UTC by d-torrance

I've finished packaging git-big-picture 1.0.0 for Debian (see https://salsa.debian.org/python-team/packages/git-big-picture).  I'm just waiting for a sponsor to upload it to Debian unstable.  Hopefully it will migrate to testing in time to be included in the next stable release (Debian 11 "Bullseye") in a few months.

One thing which you may want to include upstream is this manpage I wrote (with the help of `help2man`) for the Debian package.

2021-01-14 21:40 UTC, hartwork requested changes
Hi Doug, great initiative in general! :+1: 

I noticed that the man page included here is not based on 1.0.0 entirely: It lacks some changes from #54 from our migration to argparse. I compared with fresh output of `help2man git-big-picture` locally to be sure. Could you let `help2man` regenerate the man page from 1.0.0 `--help` output? Thanks in advance! :pray:

2021-01-14 21:42 UTC, hartwork commented
PS: The mention of `CVE-2021-3028` could help with getting in, faster.

2021-01-14 22:54 UTC, d-torrance commented
> I noticed that the man page included here is not based on 1.0.0 entirely: It lacks some changes from #54 from our migration to argparse. I compared with fresh output of `help2man git-big-picture` locally to be sure. Could you let `help2man` regenerate the man page from 1.0.0 `--help` output? Thanks in advance!

Which features is it missing?  I just double-checked and I don't see any.  Note that this isn't exactly the output of `help2man` -- I made a couple manual modifications to reduce the diff between this manpage and the one from the 0.10.0 package.

2021-01-14 23:26 UTC, hartwork commented
From `diff -u0 <(help2man git-big-picture) [..]/git-big-picture.1`:
```diff

--- /dev/fd/63  2021-01-15 00:24:28.872750550 +0100
+++ [..]/git-big-picture.1       2021-01-14 22:32:52.541402770 +0100
@@ -1,2 +1 @@
-.\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.47.16.
-.TH GIT-BIG-PICTURE "1" "January 2021" "git-big-picture 1.0.0" "User Commands"
+.TH GIT-BIG-PICTURE "1" "January 2021" "git-big-picture" "Git Manual"
@@ -4,4 +3,6 @@
-git-big-picture \- manual page for git-big-picture 1.0.0
-.SH DESCRIPTION
-usage: git\-big\-picture OPTIONS [REPOSITORY]
-.SS "positional arguments:"
+git-big-picture \- visualize git repositories
+.SH SYNOPSIS
+.B git-big-picture
+\fI\,OPTIONS \/\fR[\fI\,<repo-directory>\/\fR]
+.SH OPTIONS
+.SS Positional Arguments:
@@ -9 +10 @@
-REPOSITORY
+\fB<repo-directory>\fR
@@ -12,4 +13 @@
-.SS "optional arguments:"
-.TP
-\fB\-h\fR, \fB\-\-help\fR
-show this help message and exit
+.SS Optional Arguments:
@@ -20 +18,4 @@
-\fB\-\-pstats\fR FILE
+\fB\-h\fR, \fB\-\-help\fR
+show this help message and exit
+.TP
+\fB\-\-pstats\fR=\fI\,FILE\/\fR
@@ -25 +25,0 @@
-.SS "output options:"
@@ -26,0 +27 @@
+.SS Output Options:
@@ -29 +30 @@
-\fB\-f\fR FMT, \fB\-\-format\fR FMT
+\fB\-f\fR FMT, \fB\-\-format\fR=\fI\,FMT\/\fR
@@ -48 +49 @@
-\fB\-v\fR CMD, \fB\-\-viewer\fR CMD
+\fB\-v\fR CMD, \fB\-\-viewer\fR=\fI\,CMD\/\fR
@@ -54 +55 @@
-\fB\-o\fR FILE, \fB\-\-outfile\fR FILE
+\fB\-o\fR FILE, \fB\-\-outfile\fR=\fI\,FILE\/\fR
@@ -66 +66,0 @@
-.SS "filter options:"
@@ -67,0 +68 @@
+.SS Filter Options:
@@ -108,12 +108,0 @@
-.SH "SEE ALSO"
-The full documentation for
-.B git-big-picture
-is maintained as a Texinfo manual.  If the
-.B info
-and
-.B git-big-picture
-programs are properly installed at your site, the command
-.IP
-.B info git-big-picture
-.PP
-should give you access to the complete manual.
```

2021-01-15 02:51 UTC, d-torrance commented
Those are just the minor modifications that I made to the output of `help2man` that I mentioned above.  Everything's there, but I just did some slight reordering to and reformatting.  I'd be happy to change this PR to match `help2man`'s original output if you'd prefer.  (Although the final paragraph about the Texinfo manual should definitely go.  I'm not sure why it's the `help2man` default -- it can be left out with the `-N` command line option.)

2021-01-15 11:22 UTC, hartwork commented
> (Although the final paragraph about the Texinfo manual should definitely go. I'm not sure why it's the `help2man` default -- it can be left out with the `-N` command line option.)

`-N` is a great pointer, thanks!


> I'd be happy to change this PR to match `help2man`'s original output if you'd prefer.

I'd be glad to take your offer of matching `help2man` output for now because after this pull request I plan to (1) add a script to regenerate generate the man page file using help2man and then (2) make the CI call that script and do a diff against the file in version control to then block a merge that makes man page and --help output go out of sync. The man page will always be up to date than. I'll try the same thing with the `--help` output preview in the readme as well.

In that script we'll also be able to do any easy-to-maintain post-processing like getting `SYNOPSIS` back in. If I'd be starting from scratch, this is what I'd probably put in there for the first iteration:

```
#! /usr/bin/env bash
# <GPL v3+ header copied from run-tests-with-coverage.sh here>
help2man --no-info --name 'visualize git repositories' git-big-picture | sed 's,usage: ,,' > git-big-picture.1
```

So with that plan in mind: the closer to `help2man` output, the better for the scope of this pull request and the automation coming after.

What do you think?

2021-01-15 11:48 UTC, d-torrance commented
That sounds good to me! I just pushed a new commit replacing the manpage with the one that would be generated with the proposed script.

2021-01-15 11:54 UTC, hartwork approved these changes
Okay, great — thank you!

2021-01-15 11:55 UTC, merged

2021-01-15 11:57 UTC, d-torrance commented
One other thing for the proposed script -- you may want to set the `SOURCE_DATE_EPOCH` environment variable so that the date that appears in the manpage is reproducible.  See https://salsa.debian.org/bod/help2man/-/commit/8448110e8b7567147b70ff54ddf771306a56d39d.

2021-01-15 11:58 UTC, hartwork commented
That's a great idea, thanks for the pointer!

2021-01-20 19:08 UTC, hartwork commented
@d-torrance FYI we have just released version 1.1.1 which comes with the man page.

2021-01-20 19:11 UTC, d-torrance commented
> @d-torrance FYI we have just released version 1.1.1 which comes with the man page.

Great!  Thanks for the heads up.  We have a few more weeks before the freeze for the next stable Debian release, so I'll try to get it packaged soon!

2021-01-20 19:15 UTC, hartwork commented
Cool! I'll prey to the gods of ice, maybe that helps with the freeze :smiley: